---
title: "GDSC Cell Line Data Preprocessing"
author: "Seraphina Shi"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r load_libs,  message=FALSE, warning=FALSE} 
library(here)
library(data.table)
library(readxl)
library(dplyr)
library(gtsummary)
library(stringr)
library(ggplot2)
# library(impute)
library(gplots)
library(tidyr)
library(reshape2)
```

```{r setup}
plotFolder <- here("images", "GDSC", "02_EDA")
if(!file.exists(plotFolder)) dir.create(plotFolder,recursive=TRUE)

dataFolder <- here("data", "GDSC")
if(!file.exists(dataFolder)) dir.create(dataFolder,recursive=TRUE)

knitr::opts_chunk$set(
  cache=FALSE, autodep=FALSE, warning=FALSE, message=FALSE, echo=TRUE,
  results = 'markup', dev='png', dpi=350, fig.align = "center", fig.path = paste0(plotFolder, "/"),
  cache.path=".cache/",
  duplicate.label="allow"
)

set.seed(234)
```

```{r}
make_cdr_heatmap <- function(x, rowColor, colColor, Rowv=T, Colv=T, binary=T, title = "Cancer Drug Response"){
  
  if(binary){
    col_cdr = c("#D9B4D5", "#6BBC47")
    key_show = F
  } else {
    col_cdr = colorRampPalette(c("#D9B4D5",  "white",  "#6BBC47"))(n = 20)
    key_show = T
  }
  
  
  heatmap_cdr <- heatmap.2(
    x,
    Rowv = Rowv,  # perform hierarchical clustering on rows
    Colv = Colv,  # Perform hierarchical clustering on columns
    col = col_cdr,  # Use the custom binary colors
    dendrogram = "both",
    trace = "none",
    key = key_show,  # Disable the default color key
    RowSideColors = rowColor,
    ColSideColors = colColor,
    labRow = FALSE,  # Hide row names
    labCol = FALSE,  # Hide column names
    main = title,
    lwid = c(0.2, 5),
    lhei = c(1, 5)
  )
  
  # Add legend after creating the heatmap
  legend(y=1.15, x=0.0, xpd=TRUE, legend = c("0", "1"), fill = c("#D9B4D5", "#6BBC47"), bty = "n", cex = 0.8, title = "Sensitivity")
  
  mtext("Cance\n Types", side = 2, line = 0.5, at = 1, las = 2, cex = 0.8)
  
  return(heatmap_cdr)
}

make_cdr_heatmap_fillna_binary <- function(x, rowColor, colColor, Rowv=T, Colv=T, binary=T, title = "Cancer Drug Response"){
  
    x[is.na(x)] <- -1
    col_cdr = c("white", "#D9B4D5", "#6BBC47")
    key_show = F
  
  heatmap_cdr <- heatmap.2(
    x,
    Rowv = Rowv,  # perform hierarchical clustering on rows
    Colv = Colv,  # Perform hierarchical clustering on columns
    col = col_cdr,  # Use the custom binary colors
    dendrogram = "both",
    trace = "none",
    key = key_show,  # Disable the default color key
    RowSideColors = rowColor,
    ColSideColors = colColor,
    labRow = FALSE,  # Hide row names
    labCol = FALSE,  # Hide column names
    main = title,
    lwid = c(0.2, 5),
    lhei = c(1, 5)
  )
  
  # Add legend after creating the heatmap
  legend(y=1.15, x=0.0, xpd=TRUE, legend = c("0", "1"), fill = c("#D9B4D5", "#6BBC47"), bty = "n", cex = 0.8, title = "Sensitivity")
  
  mtext("Cance\n Types", side = 2, line = 0.5, at = 1, las = 2, cex = 0.8)
  
  return(heatmap_cdr)
}
```


# All cancer types
```{r load_data}
c_data <- read.csv(here(dataFolder, "c_data.csv"), row.names = 1)
c_meta <- read.csv(here(dataFolder, "c_meta.csv"))
d_data <- read.csv(here(dataFolder, "d_data.csv"), row.names = 1)
d_meta <- read.csv(here(dataFolder, "Drug_list2022.csv"))

d_meta <- d_meta %>% dplyr::select(Drug.Id, Name, Synonyms, Targets, Target.pathway, PubCHEM, Screening.site) %>% unique()

cdr <- read.csv(here(dataFolder, "cdr.csv"), row.names = 1)
colnames(cdr) <- gsub("^X", "",  colnames(cdr))

cat("Cancer RNAseq data dim: ", dim(c_data))
cat("Drug PCA-based feature data dim: ", dim(d_data))
cat("CDR data dim: ", dim(cdr))
```

```{r cancer_type_counts, fig.height=4, fig.width=6}

c_type_levels = c("ALL", "LAML", "LCML", # leukemia
           "CLL", "DLBC", # lymphoma
           "MM",# blood, myeloma
           "LGG", # Brain Lower Grade Glioma 	胶质瘤, nervous_system
           "GBM", # Glioblastoma multiforme	多形成性胶质细胞瘤, nervous_system
           "MB", # nervous_system
           "NB", # neoblastoma 神经母细胞瘤
           "HNSC", # head & neck 头颈鳞状细胞癌
           "SKCM", # Skin Cutaneous Melanoma	皮肤黑色素瘤
           "BRCA", # breast
           "STAD", # Stomach adenocarcinoma	胃癌
           "ESCA", # Esophageal 食管癌
           "KIRC", # Kidney
           "LIHC", # liver
           "LUAD", "LUSC", # lung, lung_NSCLC
           "SCLC", # lung
           "MESO", # Mesothelioma 间皮瘤, lung
           "COAD/READ", # colon,
           "PAAD", # Pancreatic adenocarcinoma	胰腺癌
           "THCA", # Thyroid carcinoma	甲状腺癌, thyroid
           "OV", # Ovarian serous cystadenocarcinoma	卵巢浆液性囊腺癌, urogenital_system
           "UCEC", # Uterine Corpus Endometrial Carcinoma	子宫内膜癌, urogenital_system
           "PRAD", # Prostate adenocarcinoma	前列腺癌, urogenital_system
           "BLCA", # Bladder, urogenital_system
           "CESC" # Cervical squamous cell carcinoma and endocervical adenocarcinoma 宫颈鳞癌和腺癌, urogenital_system
           ) 

c_meta$cancer_type <- factor(c_meta$cancer_type, levels = c_type_levels)


c_type_color = c("#8B2323", "#FF4040", "#FF7256","#FFD300", "#F6FF00",  # leukemia, lymphoma
                 "#00FFE5",
                 "#5800FF", "#C100FF","#AB82FF", # nervous_system
                 "#CAFF70", "#FFB6C1", "#C1FFC1", "#FFB90F",  "#AEEEEE", "#FF83FA", "#9AFF9A", "#FFBBFF", 
                 "#007BFF",  "#4876FF", "#00BFFF", "#00E5FF", # lung
                 "#FF6A00", "#BFEFFF", "#FF6EB4",
                 "#00FF7B", "#C1FF00","#58FF00",  "#CAFF70", "#00FFB0", # urogenital_system
                 "grey")

names(c_type_color) = c(c_type_levels, "NA")

count_c_type_df <- data.frame("c_type" = factor(names(c_type_color), levels = names(c_type_color)),
                              "Freq"= c(as.numeric(table(c_meta$cancer_type)), sum(is.na(c_meta$cancer_type))),
                              "c_type_color" = c_type_color)

ggplot(count_c_type_df, aes(c_type, Freq, fill = c_type)) +
  geom_col() + 
  scale_x_discrete(limits=rev) + 
  coord_flip() + 
  scale_fill_manual(values = count_c_type_df$c_type_color) +
  theme_bw() + 
  theme(legend.position = "none") +
  labs(x = "Cancer type", y = "Frequency")
```

```{r}
map_value_to_color <- function(x) {
  if (is.na(x)) {
    return("darkgray")  # Missing values (NA) will be gray
  } else if (x == "0") {
    return("#E89DA0")   # 0 will be red
  } else if (x == "1") {
    return("#80C1C4") # 1 will be green
  } else {
    return("#B696B6")  # Other values will be blue
  }
}

c_colors <- rep(count_c_type_df$c_type_color, count_c_type_df$Freq)
```

```{r all_cdr_heatmap, fig.height=6, fig.width=10}
set.seed(123)
heatmap_all <- heatmap.2(
  as.matrix(cdr),
  Rowv = FALSE,  # Do not perform hierarchical clustering on rows
  Colv = TRUE,  # Perform hierarchical clustering on columns
  col = c("#D9B4D5", "#6BBC47"),  # Use the custom binary colors
  dendrogram = "both",
  trace = "none",
  key = FALSE,  # Disable the default color key
  RowSideColors = c_colors,  # Row annotation color
  labRow = FALSE,  # Hide row names
  labCol = FALSE,  # Hide column names
  main = "Cancer Drug Response",
  lwid = c(0.2, 5)
)

# Add legend after creating the heatmap
legend(y=1.1, x=-0.075, xpd=TRUE, legend = c("0", "1"), fill = c("#D9B4D5", "#6BBC47"), bty = "n", cex = 0.8, title = "Sensitivity")

mtext("Cance\n Types", side = 2, line = 0.5, at = 0.85, las = 2, cex = 0.8) # Add title to RowSideColors
# mtext(text = c_type_levels, side = 2, line = 1, at = seq(0, 1, length.out = length(c_type_levels) + 1) - 0.5/length(c_type_levels), las = 2, cex = 0.8)
```

# Lung
```{r}
c_types <- c("LUAD","LUSC", "SCLC",  "MESO")

c_meta_lung <- c_meta[c_meta$cancer_type %in% c_types, ]

c_data_lung <- c_data[c_meta_lung$COSMIC_ID, ]
cdr_lung <- cdr[as.character(c_meta_lung$COSMIC_ID), ]

c_colors_lung <- c(rep("lightblue", nrow(c_data_lung)))
```

```{r lung_cdr_heatmap, fig.height=6, fig.width=10}
cdr_tmp = as.matrix(cdr_lung)
    
cdr_row_color = c_colors_lung
cdr_col_color = rep('white', ncol(cdr_tmp))

cdr_heatmap_hier = make_cdr_heatmap(cdr_tmp, cdr_row_color, cdr_col_color, F, F)
```


```{r lung_cdr_heatmap_clust_2, fig.height=6, fig.width=10}
cdr_heatmap_hier = make_cdr_heatmap_fillna_binary(cdr_tmp, cdr_row_color, cdr_col_color, T, T)
```

## BCPlaid
```{r warning=F, message=FALSE}
library("biclust")

cdr_bi <- cdr_tmp
cdr_bi[is.na(cdr_bi)] = -1
cdr_bi <- as.matrix(cdr_bi)
```

```{r}
bicResult <- biclust(cdr_bi, method=BCPlaid(), background = F, verbose=FALSE)
heatmapBC(cdr_bi, bicResult)

bicResult <- biclust(cdr_bi, method=BCPlaid(), background = F, verbose=FALSE,
                     row.release = 0.5, col.release = 0.5)
heatmapBC(cdr_bi, bicResult)


bicResult <- biclust(cdr_bi, method=BCPlaid(), background = F, verbose=FALSE,
                     row.release = 0.6, col.release = 0.5)
heatmapBC(cdr_bi, bicResult)

bicResult <- biclust(cdr_bi, method=BCPlaid(), background = F, verbose=FALSE,
                     row.release = 0.6, col.release = 0.6)
heatmapBC(cdr_bi, bicResult)
```

```{r}
bicResult <- biclust(cdr_bi, method=BCPlaid(), background = F, verbose=FALSE,
                     row.release = 0.8, col.release = 0.8)
heatmapBC(cdr_bi, bicResult)

bicResult <- biclust(cdr_bi, method=BCPlaid(), background = TRUE, verbose=FALSE,
                     row.release = 0.5, col.release = 0.5)
heatmapBC(cdr_bi, bicResult)

bicResult <- biclust(cdr_bi, method=BCPlaid(), background = TRUE, verbose=FALSE,
                     row.release = 0.6, col.release = 0.5)
heatmapBC(cdr_bi, bicResult)
```



# Breast
```{r}
c_types <- c("BRCA")

c_meta_breast <- c_meta[c_meta$cancer_type %in% c_types, ]

c_data_breast <- c_data[c_meta_breast$COSMIC_ID, ]
cdr_breast <- cdr[as.character(c_meta_breast$COSMIC_ID), ]

c_colors_breast <- c(rep("#FFB90F", nrow(c_data_breast)))
```

```{r breast_cdr_heatmap, fig.height=6, fig.width=10}
cdr_tmp = as.matrix(cdr_breast)
    
cdr_row_color = c_colors_breast
cdr_col_color = rep('white', ncol(cdr_tmp))

cdr_heatmap_hier = make_cdr_heatmap(cdr_tmp, cdr_row_color, cdr_col_color, F, F)
```


```{r breast_cdr_heatmap_clust_2, fig.height=6, fig.width=10}
cdr_heatmap_hier = make_cdr_heatmap_fillna_binary(cdr_tmp, cdr_row_color, cdr_col_color, T, T)
```

## BCPlaid
```{r warning=F, message=FALSE}
library("biclust")

cdr_bi <- cdr_tmp
cdr_bi[is.na(cdr_bi)] = -1
cdr_bi <- as.matrix(cdr_bi)
```

```{r}
set.seed(12)

bicResult <- biclust(cdr_bi, method=BCPlaid(), background = F, verbose=FALSE,
                     row.release = 0.5, col.release = 0.5)
heatmapBC(cdr_bi, bicResult)

bicResult <- biclust(cdr_bi, method=BCPlaid(), background = F, verbose=FALSE,
                     row.release = 0.5, col.release = 0.7)
heatmapBC(cdr_bi, bicResult)


bicResult <- biclust(cdr_bi, method=BCPlaid(), background = F, verbose=FALSE,
                     row.release = 0.6, col.release = 0.5)
heatmapBC(cdr_bi, bicResult)

```

```{r}
bicResult <- biclust(cdr_bi, method=BCPlaid(), background = TRUE, verbose=FALSE,
                     row.release = 0.5, col.release = 0.5)
heatmapBC(cdr_bi, bicResult)

bicResult <- biclust(cdr_bi, method=BCPlaid(), background = TRUE, verbose=FALSE,
                     row.release = 0.6, col.release = 0.5)
heatmapBC(cdr_bi, bicResult)
```




# Colon
```{r}
c_types <- c("COAD/READ")

c_meta_colon <- c_meta[c_meta$cancer_type %in% c_types, ]

c_data_colon <- c_data[c_meta_colon$COSMIC_ID, ]
cdr_colon <- cdr[as.character(c_meta_colon$COSMIC_ID), ]

c_colors_colon <- c(rep(c_type_color["COAD/READ"], nrow(c_data_colon)))
```

```{r colon_cdr_heatmap, fig.height=6, fig.width=10}
cdr_tmp = as.matrix(cdr_colon)
    
cdr_row_color = c_colors_colon
cdr_col_color = rep('white', ncol(cdr_tmp))

cdr_heatmap_hier = make_cdr_heatmap(cdr_tmp, cdr_row_color, cdr_col_color, F, F)
```


```{r colon_cdr_heatmap_clust_2, fig.height=6, fig.width=10}
cdr_heatmap_hier = make_cdr_heatmap_fillna_binary(cdr_tmp, cdr_row_color, cdr_col_color, T, T)
```

## BCPlaid
```{r warning=F, message=FALSE}
library("biclust")

cdr_bi <- cdr_tmp
cdr_bi[is.na(cdr_bi)] = -1
cdr_bi <- as.matrix(cdr_bi)
```

```{r}
set.seed(12)

bicResult <- biclust(cdr_bi, method=BCPlaid(), background = F, verbose=FALSE,
                     row.release = 0.5, col.release = 0.5)
heatmapBC(cdr_bi, bicResult)

bicResult <- biclust(cdr_bi, method=BCPlaid(), background = F, verbose=FALSE,
                     row.release = 0.5, col.release = 0.7)
heatmapBC(cdr_bi, bicResult)


bicResult <- biclust(cdr_bi, method=BCPlaid(), background = F, verbose=FALSE,
                     row.release = 0.6, col.release = 0.5)
heatmapBC(cdr_bi, bicResult)

```

```{r}
bicResult <- biclust(cdr_bi, method=BCPlaid(), background = TRUE, verbose=FALSE,
                     row.release = 0.5, col.release = 0.5)
heatmapBC(cdr_bi, bicResult)

# bicResult <- biclust(cdr_bi, method=BCPlaid(), background = TRUE, verbose=FALSE,
#                      row.release = 0.6, col.release = 0.5)
# heatmapBC(cdr_bi, bicResult)
```


